name: s3-deploy
on:
  pull_request:
    branches:
      - publish
    types: [opened, synchronize, closed]

jobs:
  UploadContents:
    name: Upload static files
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: S3 sync
        working-directory: contents
        run: aws s3 sync . s3://hikapo.com --delete --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers --exclude "README.md"

  AnotherJob:
